---
title: "The overlooked: an analysis of the sample population of Toronto's 2017 multilingual policy survey"
author: "Haili Su"
date: "2020-09-27"
bibliography: "reference_su.bib"
categories: ["R"]
tags: ["R Markdown", "plot", "regression"]

---



<p>The R Markdown file for this post, including all the codes can be found <a href="https://github.com/hlisu/sta_304/blob/master/content/post/blog_post_ps1.Rmd">here</a> on my <a href="https://github.com/hlisu/">GitHub</a>.</p>
<div id="abstract" class="section level1">
<h1>Abstract</h1>
<p>In 2017, the City of Toronto conducted a survey on its multilingual information policy. In this article I will analyse two demographic groups that shows unusal patterns: seniors, especially those who are over 85, and Bengali speakers, who are overrepresented in the survey results, and how they responded to the survey. Through the analysis I will discuss how the sampled population of this survey doesn’t necessarily reflect the target population.</p>
</div>
<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>The multicultural nature of Toronto’s communities determines that the city government needs to provide information and services in different languages to serve its multilingual constituents. In 2017 the City of Toronto conducted an online survey to solicit feedbacks and suggestions from the public on its policy of providing information in languages other than English.</p>
<p>The survey was offered in 14 languages that, according to the City, was the 14 most spoken at home by Torontonians, per 2011 census data (City of Toronto, 2017). The population who are targeted are people who might have the need to access City information in (a) non-English language(s), predominantly Torontonians with multilingual backgrounds. However, does the sample population, who participate in this survey voluntarily (“sample of volunteers”), really reflect the multilingual communities in the city?</p>
<p>To answer this question, in this analysis I will look at two groups in the population: the non-English speaking seniors, who are underrepresented in this survey, and the Bengali speakers who are overrepresented. I will focus on the ways that they found out about the survey as they reported. I will also examine if there are differences in terms of satisfactions with the City’s multilingual service between the respondents answered in Bengali and other respondents.</p>
<p>Here we access the dataset on the City of Toronto’s open data patrol through <span class="citation">Gelfand (2020)</span>.
The data I analyzed include the responses to</p>
<ol style="list-style-type: decimal">
<li><p>Question 2: “If you were accessing translated City Information” and follow-ups;</p></li>
<li><p>Question 3: ’Have you ever asked the City to translate information for you?&quot; and follow-ups;</p></li>
<li><p>Question 8: What language(s) do you know enough to use comfortably at home or work?</p></li>
<li><p>Question 11: How did you find out about this survey?</p></li>
</ol>
<p>along with the language that each respondent chose for the survey, their ages and postal codes. A complete list of survey questions can be found on the open data patrol’s webpage for this survey. Here is a quick look of the dataset after cleansing and reorganization:</p>
<pre><code>## Observations: 1,228
## Variables: 11
## $ survey_language    &lt;chr&gt; &quot;Spanish&quot;, &quot;Urdu&quot;, &quot;English&quot;, &quot;English&quot;, &quot;English&quot;…
## $ Q2                 &lt;chr&gt; &quot;No&quot;, &quot;Yes&quot;, &quot;No&quot;, &quot;Yes&quot;, &quot;No&quot;, &quot;No&quot;, &quot;No&quot;, &quot;No&quot;, …
## $ Q2_Y_Success       &lt;chr&gt; NA, NA, NA, &quot;Yes&quot;, NA, NA, NA, NA, NA, NA, NA, &quot;No…
## $ Q2_Y_Satisfication &lt;chr&gt; NA, NA, NA, &quot;Very Satisfied&quot;, NA, NA, NA, NA, NA, …
## $ Q2_N_Why           &lt;chr&gt; NA, NA, &quot;Didn&#39;t require it&quot;, NA, &quot;Didn&#39;t require i…
## $ Q3                 &lt;chr&gt; &quot;No&quot;, NA, &quot;No&quot;, &quot;No&quot;, &quot;No&quot;, &quot;No&quot;, &quot;No&quot;, &quot;Yes&quot;, &quot;No…
## $ Q3_Y               &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, &quot;Yes to my satisfactio…
## $ age                &lt;chr&gt; NA, NA, &quot;35 - 44&quot;, &quot;15 - 24&quot;, &quot;15 - 24&quot;, &quot;15 - 24&quot;…
## $ postal             &lt;chr&gt; NA, NA, &quot;M4C&quot;, &quot;M5H&quot;, &quot;M1M&quot;, &quot;m4c&quot;, &quot;M5H&quot;, NA, &quot;M1…
## $ Q8                 &lt;chr&gt; NA, NA, &quot;English only&quot;, &quot;English and another langu…
## $ Q11                &lt;chr&gt; NA, NA, &quot;City staff&quot;, &quot;From a friend, family membe…</code></pre>
</div>
<div id="part-i-non-english-speaking-seniors" class="section level1">
<h1>Part I: Non-English Speaking Seniors</h1>
<div id="data" class="section level2">
<h2>Data</h2>
<p>The age make-up of our 1228 respondents is as shown below:</p>
<pre><code>## # A tibble: 9 x 3
##   age         n    prop
##   &lt;chr&gt;   &lt;int&gt;   &lt;dbl&gt;
## 1 15 - 24   117 0.0953 
## 2 25 - 34   222 0.181  
## 3 35 - 44   327 0.266  
## 4 45 - 54   286 0.233  
## 5 55 - 64   148 0.121  
## 6 65 - 74    43 0.0350 
## 7 75 - 84     8 0.00651
## 8 85+        56 0.0456 
## 9 &lt;NA&gt;       21 0.0171</code></pre>
<p>While the 65+ population is underrepresented in the survey results (8.7% of the respondents. 15.6% of Torontonians are over 65 according to 2016 census (Statistics Canada, 2017)), 85+ (2.4% of the population (Statistics Canada, 2017)) are actually overrepresented.</p>
<p>And how about their language use habit at home? Let’s look at how each age group responded to question 8: What language(s) do you know enough to use comfortably at home or work?</p>
<p><img src="/post/blog_post_ps1_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>As the graph shows, most of the respondents are comfortable with speaking English and another language at home. However, among the group of 85+, the pattern is different: more respondents can only speak English, and no one can only speak a non-English language. This demographic make-up differs from other age group, especially the closest age group with comparable sample size, the 65-74 years old.</p>
<p>And how did the elderly (65+) respondents learn about this survey? Here is a bar chart showing how the three senior age groups in the survey answered question 11: ow did you find out about this survey?
<img src="/post/blog_post_ps1_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>The data here show a peculiar pattern.While most of respondent who report their age group as 65-74 know about the survey from Mayor’s or City Councillor’s official communication means, most of the 85+ respondents find out about the survey from online website. Due to the small sample size of 75-84 age group, there isn’t a communicating method that’s outstanding.</p>
</div>
<div id="discussion" class="section level2">
<h2>Discussion</h2>
<p>Toronto has a long history of immigration from non-English speaking countries. The long histories of Chinatown, Little Italy, Greektown and many other neighbourhoods are the proofs. While it is imaginable that most of senior immigrants have acquired English through living here for a long period of time, the majority of the 85+ respondents here are only comfortable with speaking English at home or at work. While, in fact, the City’s so-called “Seniors Strategy 2.0” report highlighted that about 15% of Toronto’s over 65 population have no knowledge of English (City of Toronto, 2018). There is a real concern that Toronto’s multilingual and non-English speaking seniors, who are more likely to rely on translated information from the City, are overlooked by the survey.</p>
<p>Why didn’t this survey reach enough multilingual and non-English speaking seniors? The ways that the senior respondents in this survey found out about it, shown in fig 2, may offer a clue. Based on these data the elder respondents are more likely people who have access to internet and are less likely to have been discouraged from local governance due to language barrier. Immigrant seniors, who are usually not native speakers of English, may encountered more barriers and challenges comparing to their Canadian-born peers (Stewart et al., 2011), which means they may encounter more difficulties in finding out and participating in a survey like this. The City should probably look into developing better outreach approach with multilingual and non-English speaking seniors in Toronto, especially when they’re consulting the public on multilingual policy.</p>
</div>
</div>
<div id="part-ii-bengali-speakers" class="section level1">
<h1>Part II Bengali Speakers</h1>
<div id="data-1" class="section level2">
<h2>Data</h2>
<p>The survey was offered in 14 languages are most spoken at home in Toronto in 2011 census. Here are the figures of how many people chose to answer in each of these languages:</p>
<pre><code>## # A tibble: 10 x 3
##    survey_language          n     prop
##    &lt;chr&gt;                &lt;int&gt;    &lt;dbl&gt;
##  1 Bengali                198 0.161   
##  2 Chinese (Simplified)     4 0.00326 
##  3 English               1002 0.816   
##  4 French                   6 0.00489 
##  5 Italian                  1 0.000814
##  6 Korean                   1 0.000814
##  7 Portuguese               4 0.00326 
##  8 Russian                  1 0.000814
##  9 Spanish                  9 0.00733 
## 10 Urdu                     2 0.00163</code></pre>
<p>As we can see most of the respondents chose to answer the questions in English, while no one completed the survey in Tagalog, Tamil, Farsi and Somali. However, the number of people who chose to answer in Bengali (n = 198) seems significantly higher than all other non-English language responses adding up (n = 28).</p>
</div>
<div id="discussion-1" class="section level2">
<h2>Discussion</h2>
<p>The respondents who almost certainly know Bengali (since they answered the Bengali version) are 16.1% of all the respondents. Considering in 2016 census 0.7% of Torontonians speak Bengali most often at home in 2016 census (comparing to 3.3% for Mandarin and 0.7% for French) (Statistics Canada, 2017), and the fact that some Bengali speakers may choose to answer in English, Bengali speakers are apparently overrepresented in this survey. So how did this happen?</p>
<p>First, I should acknowledge that most of the people who chose to answer in English can speak at least one non-English language at home or at work. As this graph demonstrates:
<img src="/post/blog_post_ps1_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>So, this survey definitely reached many members of Toronto’s multilingual communities, and most of them chose to take the English version. However, Bengali speakers seems much more willing to take the Bengali version survey comparing to other non-English languages. Does this mean Bengali speakers generally have more satisfactory experiences with the City’s translation service and probably use it more (thus more Bengali speakers knew and responded to the survey?)? I selected two questions to examine this possibility. First is a secondary follow up for Q2: How satisfied were you with your experience in getting information in another language?
<img src="/post/blog_post_ps1_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>From this graph it seems there is no difference in the pattern of responses to this question between Bengali speakers and other respondents. How about the follow-up to Q3: If you answered “Yes” (that you have requested city to translate information for you), did the City translate the information?
<img src="/post/blog_post_ps1_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>Again, there’s virtually no distinction between the response patterns. Bengali respondents’ experiences with the City’s translation service is so consistent with the rest of the respondents that I checked my codes multiple times to make sure I didn’t mess up and end up showing the same graph twice.</p>
<p>While the City of Toronto may have to review why they didn’t translate most of the information people requested them to, they should also look into how respondents are recruited. Did more Bengali speakers answer the survey because Bengali-speaking community organizations advertised the survey more than other communities or is it due to some other reasons? Here is Bengali speaker’s answers to Question 11, How did you find out about this survey, comparing to other respondents:
<img src="/post/blog_post_ps1_files/figure-html/unnamed-chunk-10-1.png" width="672" /><img src="/post/blog_post_ps1_files/figure-html/unnamed-chunk-10-2.png" width="672" /></p>
<p>Apparently, a significantly larger portion of the respondents who answered in Bengali learnt about the survey from social media, while other respondents show a more discrete pattern. Could this be the effort of a Facebook post from a community organization, or did the city buy more Facebook ads for this survey in Bengali than in other non-English language?</p>
<p>Bengali-speaking community’s engagement in the City’s multilingual policy development process is, undoubtfully, much needed and highly appreciable. However, if the City would like this or similar future surveys to better reflect the target population, i.e. the Torontonians, they should probably look into it, and think about how to encourage more members from other minority language communities to engage in the process. Especially when no one took the survey in Tagalog (spoken most often at home by 1.6% of the population, per 2016 census), Tamil (1.5%), Farsi (1.3%) and Somali (0.2%) (Statistics Canada, 2017), though it shouldn’t be interpreted as that people who speak these languages didn’t take the survey.</p>
</div>
</div>
<div id="weakness-next-steps" class="section level1">
<h1>Weakness &amp; Next Steps</h1>
<p>Given the survey use the sample of volunteers method, and the fact that the survey completion process could be unsupervised, the overrepresentation of a certain group could be the results of small group of individuals trying to manipulate the results. However, since the responses to the non-demographic questions didn’t show any abnormal patterns, those responses should be reliable.</p>
<p>Also, a flaw in my analysis on the senior population is that, I don’t have more concrete, data-based evidence to support the reasoning that the seniors who took the survey are better off than average. One possible way to further analyze it is to examine the geographical distribution of the respondents based on the postal codes they provided and compare the average incomes in those areas. However, despite the survey only asked for the first three digits, many people answered their full postal codes (and one person even filled in “New Zealand”). Therefore, though it is not impossible, it requires a lot of data cleansing and recategorization.</p>
<p>Lastly, although people who can comfortably use language(s) other than English had been asked to fill in the other language(s) they can speak, I didn’t analyze those data. This is because many people filled in more than one language(s) while the questions only asked for one – they seem to misinterpret it as asking all the languages they can speak. Also some people provided joke answers (“British”), or answered in another language (since they took the survey in that language). Therefore even though utilize can give a much better picture of the composition of the sample population, it would also require a lot of data cleansing. If I have more time these will be where I want to conduct further analysis on.</p>
</div>
<div id="reference" class="section level1">
<h1>Reference</h1>
<p>City of Toronto. 2017. <em>Multilingual Policy - Language Survey</em>. <em>City of Toronto Open Data Portal</em>. Toronto. Released March 31, 2017. <a href="https://open.toronto.ca/dataset/multilingual-policy-language-survey/" class="uri">https://open.toronto.ca/dataset/multilingual-policy-language-survey/</a></p>
<p>Statistics Canada. 2017. <em>Toronto, C [Census subdivision], Ontario and Canada [Country] (table)</em>. <em>Census Profile</em>. 2016 Census. Statistics Canada Catalogue no. 98-316-X2016001. Ottawa. Released November 29, 2017.
<a href="https://www12.statcan.gc.ca/census-recensement/2016/dp-pd/prof/index.cfm?Lang=E" class="uri">https://www12.statcan.gc.ca/census-recensement/2016/dp-pd/prof/index.cfm?Lang=E</a> (accessed September 27, 2020).</p>
<p>City of Toronto. 2018. <em>Toronto Seniors Straegy 2.0</em>. Toronto. <a href="https://www.toronto.ca/wp-content/uploads/2019/02/93cd-CoT-seniors-strategy2.pdf" class="uri">https://www.toronto.ca/wp-content/uploads/2019/02/93cd-CoT-seniors-strategy2.pdf</a>.</p>
<p>Stewart, M., Shizha, E., Makwarimba, E., Spitzer, D., Khalema, E.N. and Nsaliwa, C.D. (2011), “Challenges and barriers to services for immigrant seniors in Canada: “you are among others but you feel alone”&quot;, International Journal of Migration, Health and Social Care, Vol. 7 No. 1, pp. 16-32. <a href="https://doi.org/10.1108/17479891111176278" class="uri">https://doi.org/10.1108/17479891111176278</a></p>
<div id="refs" class="references">
<div id="ref-copento">
<p>Gelfand, Sharla. 2020. <em>Opendatatoronto: Access the City of Toronto Open Data Portal</em>. <a href="https://CRAN.R-project.org/package=opendatatoronto">https://CRAN.R-project.org/package=opendatatoronto</a>.</p>
</div>
</div>
</div>
